---
output:
  pdf_document:
    latex_engine: lualatex
    template: /home/landongetz/Nextcloud/CV/CV-latex/LJG-latex-cv.tex

geometry: margin=0.75in

title: "CV"
author: Dr. Landon J. Getz (PhD)

jobtitle: "**Postdoctoral Fellow**"
address: "Department of Biochemistry | Temerty Faculty of Medicine | University of Toronto"
address2: "MaRS Centre, West Tower | 661 University Avenue, Suite 1600 | Toronto, Ontario, M5G 1M1"
#fontawesome: yes
fontawesome5: yes
email: landon.getz@utoronto.ca
#github: landongetz
twitter: landongetz
orcid: "0000-0002-3841-1062"
#phone: "+353 1 408 4800"
web: landongetz.com
updated: no

keywords: R Markdown, academic CV, template

#fontfamily: Georgia
#fontfamilyoptions:
#mainfont: Georgia
fontsize: 10pt
linkcolor: blue
urlcolor: blue
---
$\\$

>Dr. Landon J. Getz (PhD) is a Postdoctoral Fellow in the Maxwell Lab at the University of Toronto's Department of Biochemistry. Dr. Getz obtained his Ph.D. in Microbiology and Immunoloty at Dalhousie University in the lab of Dr. Nikhil Thomas, studying *Vibrio* genetics and host-pathogen interactions. Landon completed his B.Sc honours degree, as well as a certificate in Genetics, in 2017, also from Dalhousie University. Dr. Getz is a Vanier Scholar (2019), Killam Laureate (2019), and a member of the Chief Science Advisor's inaugural youth council (2020).
>
>Dr. Getz has a keen interest in understanding the genetic mechanisms of bacterial-environmental survival and the genetic and molecular mechanisms of pathogenesis and phage-predation in *Vibrio* species. Dr. Getz has explored the pathogenecity and environmental survival of *Vibrio parahaemolyticus* and the genetics of Type III Secretion System biogenesis in both *V. parahaemolyticus* and Enteropathogenic *E. coli*. Dr. Getz is also deeply interested in the intersections between science and society, and uses this interest to pursue the ethical and policy implications of new and emerging medical and genetic technologies, such as CRISPR/Cas. Consequently, Dr. Getz has published several peer-reviewed journal articles and commentaries on both microbial genetics and pathogenesis, as well as in bioethics.

# Education
*Termerty Faculty of Medicine, University of Toronto*, Postdoctoral Fellow - Lab of Dr. Karen Maxwell \hfill \textit{Present}

*Faculty of Medicine, Dalhousie University*, Ph.D. in Microbiology & Immunology \hfill 2022

*Cold Spring Harbor Laboratory Course*, on Advanced Bacterial Genetics \hfill 2019

*Faculty of Science, Dalhousie University*, B.Sc. Microbiology & Immunology \hfill 2017$\\$
\hspace*{5mm}  First Class Honours - cGPA > 3.7 $\\$
\hspace*{5mm}  Department of Microbiology and Immmunology Honours Student Research Prize

*Faculty of Science, Dalhousie University*, Certificate in Genetics \hfill 2017

# Publications
> Career Total (Published): 8 $\\$
> 106 Citations; h-index: 6 (as per Google Scholar)

## Journal Articles

*Corresponding Author*^\#^ | *Equal Contribution^\*^ (ordered alphabetically)*

\begin{etaremune}
\renewcommand\labelenumi{\bfseries\theenumi .}
 \item \textbf{Getz, L.J.}, Brown, J.M., Sobot, L., Chow, A., Mahendrarajah, J., Thomas, N.A.\textsuperscript{\#} (2022). Attenuation of a DNA Cruciform by a Conserved Regulator Directs T3SS-1 mediated virulence in \textit{Vibrio parahaemolyticus}. Under Revision at Nucleic Acids Research.
 \item Kratzer, K.\*, \textbf{Getz, L.J.}, Peterlini, T, Masson\textsuperscript{\#}, J-Y, Dellaire, G\textsuperscript{\#} (2021). \href{https://link.springer.com/article/10.1007/s00439-021-02272-5}{"Addressing the dark matter of gene therapy: technical and ethical barriers to clinical application."} \textit{Human Genetics}. DOI: 0.1007/s00439-021-02272-5
 \item \textbf{Getz, L.J.}, Dellaire, G.\textsuperscript{\#} (2020). \href{https://link.springer.com/article/10.1007/s11948-020-00226-0}{"Back to Basics: Application of the 4-principle approach to bioethics to heritable genome editing."} \textit{Science and Engineering Ethics}. DOI: 10.1007/s11948-020-00226-0
 \item \textbf{Getz, L.J.}, Runté, C., Rainey, J., Thomas, N.A.\textsuperscript{\#} (2019). \href{https://jb.asm.org/content/201/19/e00205-19}{"Tyrosine phosphorylation as a widespread regulatory mechanism in prokaryotes."} \textit{Journal of Bacteriology}. DOI: 10.1128/JB.00205-19
 \item Thornbury, M.\*, Sicheri, J.\*, Slaine, P.D., \textbf{Getz, L.J.}, Finlayson-Trick, E.C.L., Cook, J., Guinard, C., Boudreau, N., Jakeman, D., Rohde, J.R., McCormick, C.\textsuperscript{\#} (2018). \href{https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0209221}{"Characterization of novel lignocellulose-degrading enzymes from the porcupine microbiome using synthetic metagenomics"} \textit{PLoS One}. DOI: 10.1371/journal.pone.0209221
 \item \textbf{Getz, L.J.\textsuperscript{\#}}, Dellaire, G.\textsuperscript{\#} (2018). \href{https://www.cell.com/trends/biotechnology/fulltext/S0167-7799(18)30207-5}{"Angels and Devils: Dual-Use in Biotechnology."} \textit{Trends in Biotechnology}. DOI: 10.1016/j.tibtech.2018.07.016
 \item Runté, C., Jain, U., \textbf{Getz, L.J.}, Secord, S., Kuwae, A., Abe, A., Leblanc, J., Stadnyk, A.W., Kaper, J.B., Hansen, A.M., Thomas, N.A.\textsuperscript{\#} (2018). \href{http://onlinelibrary.wiley.com/doi/10.1111/mmi.13948/full}{"Tandem tyrosine phosphosites in the enteropathogenic \textit{Escherichia coli} chaperone CesT are required for differential type III effector translocation and virulence."} \textit{Molecular Microbiology}. DOI: 10.1111/mmi.13948
 \item \textbf{Getz, L.J.} Thomas, N.A.\textsuperscript{\#} (2018). \href{http://jb.asm.org/content/200/15/e00653-17.abstract}{"The Transcriptional Regulator HlyU is a Positive Regulator for Expression of \textit{exsA} Leading to Type III Secretion System-1 Activation in \textit{Vibrio parahaemolyticus}"} \textit{Journal of Bacteriology}. DOI: 10.1128/JB.00653-17
 \item \textbf{Getz, L.J.}, Finlayson-Trick, E.C.L.\*, Slaine, P.D.\*, Thornbury, M., Lamourerux, E., Cook, J., Langille, M.G.I., Murray, L.E., McCormick, C., Rohde, J.R., Cheng, Z.\textsuperscript{\#} (2017). \href{http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0189404}{"Taxonomic differences of gut microbiomes drive cellulolytic enzymatic potential within hind-gut fermenting mammals."} \textit{PLoS One}. DOI: 10.1371/journal.pone.0189404
 \end{etaremune}

## Theses
\begin{etaremune}
\renewcommand\labelenumi{\bfseries\theenumi .}
  \item \textbf{Getz, L.J.} (2022) \href{https://dalspace.library.dal.ca/handle/10222/81872}{"Genome-wide Investigation of \textit{Vibrio parahaemolyticus} Type III Secretion System-1 Regulation and Chitin Metabolism"} \textit{Ph.D.} Dalhousie University, Halifax, NS, Canada.
  \item \textbf{Getz, L.J.} (2017) "A Genetic Switch Controls the Type III Secretion System Master Regulator, ExsA, in \textit{Vibrio parahaemolyticus} RIMD2210633". \textit{B.Sc. (Hons)} Dalhousie University, Halifax, NS, Canada.
\end{etaremune}

## Commentary

\begin{etaremune}
\renewcommand\labelenumi{\bfseries\theenumi .}
\item Baylis, F., \textbf{Getz, L.J.} (2021). [Challenge studies for COVID-19: Now is still not the time.](https://blogs.bmj.com/medical-ethics/2021/04/27/challenge-studies-for-covid-19-now-is-still-not-the-time/) JME Blog
\item \textbf{Getz, L.J.}, Baylis, F. (2021). [Challenge studies for COVID-19: Now is not the time.](https://blogs.bmj.com/medical-ethics/2021/04/06/challenge-studies-for-covid-19-now-is-not-the-time/) JME Blog
\item \textbf{Getz, L.J.}, Baylis, F. (2020). [Canada should reject the idea of deliberately infecting vaccine volunteers.](https://policyoptions.irpp.org/magazines/november-2020/canada-should-reject-the-idea-of-deliberately-infecting-vaccine-volunteers/) PolicyOptions.ca.
\item Baylis, F., \textbf{Getz, L.J.} (2020). [Why federal government should reject human challenge trials for COVID-19 vaccine.](https://www.cbc.ca/news/opinion/opinion-covid-vaccine-human-challenge-trials-1.5790713) CBC Opinion.
\item Qaiser, F., Morriseau, T., Rilling, M., Cartile, A., Sung, M., \textbf{Getz, L.J.}, Boulanger, M-E. (2020). [Envisioning A Post-Pandemic Future in the Canadian Science Community: A Youth Perspective.](https://sciencepolicy.ca/posts/envisioning-a-post-pandemic-future-in-the-canadian-science-community-a-youth-perspective/) Canadian Science Policy Conference 2020.
\item Baylis, F., \textbf{Getz, L.J.} (2020). [Rush to risky chellenge trials is unethical.](https://healthydebate.ca/2020/10/topic/risky-challenge-trials-unethical/) HealthyDebate.ca.
\item \textbf{Getz, L.J.} (2020). [Rushing coronavirus vaccines and treatments could do more harm than good.](https://theconversation.com/rushing-coronavirus-vaccines-and-treatments-could-do-more-harm-than-good-136449) TheConversation.ca, Republished in Everything Zoomer, and Dal News.
\item Kofler, N., \textbf{Getz, L.J.}, Baylis, F., Dellaire, G. (2019). [Genetically modifying mosquitoes to control the spread of disease carries unknown risks.](https://theconversation.com/genetically-modifying-mosquitoes-to-control-the-spread-of-disease-carries-unknown-risks-123862) TheConversation.ca, republished in Salon, HalifaxToday.ca, SaltWire Newspapers, and Gannett Newspapers.
\item \textbf{Getz, L.J.}, Dellaire, G. (2019). [Moratorium on Human Genome Editing: Time to Get It Right.](https://www.thehastingscenter.org/moratorium-on-human-genome-editing-time-to-get-it-right/) The Hastings Center Forum Blog.
\item  \textbf{Getz, L.J.}, Dellaire, G. (2019). [CRISPR gene editing: Why we need Slow Science.](https://theconversation.com/crispr-gene-editing-why-we-need-slow-science-113639) The Conversation.ca.
\item  \textbf{Getz, L.J.} (2019). [The "Value" of Consumer DNA Sequencing.](https://impactethics.ca/2019/02/28/the-value-of-consumer-dna-sequencing/) Impact Ethics at Novel Tech Ethics.
\item  \textbf{Getz, L.J.}, Dellaire, G., Baylis, F. (2018). [Jiankui He: A Sorry Tale of High-Stakes Science.](https://www.thehastingscenter.org/jiankui-sorry-tale-high-stakes-science/) The Hastings Center Forum Blog.
\item  Baylis, F., Dellaire, G., \textbf{Getz, L.J.} (2018). [Why we are not ready for genetically designed babies.](https://theconversation.com/why-we-are-not-ready-for-genetically-designed-babies-107756) The Conversation.ca. Reprinted in: The National Post and the Halifax Chronicle Herald.
\item  \textbf{Getz, L.J.} (2018). [Thicker Than Water: Slow Movement on Blood Policy.](https://impactethics.ca/2018/10/26/thicker-than-water-slow-movement-on-blood-policy/) Impact Ethics at Novel Tech Ethics.
\item  \textbf{Getz, L.J.} (2018). [The Privacy Implications of Human DNA Sequencing.](https://impactethics.ca/2018/05/11/the-privacy-implications-of-human-dna-sequencing/) Impact Ethics at Novel Tech Ethics.
\item  \textbf{Getz, L.J.} (2017). [A Reflection on Blood Donation Policy in Canada.](https://impactethics.ca/2017/08/24/a-reflection-on-blood-donation-policy-in-canada/) Impact Ethics at Novel Tech Ethics. Reprinted at the Kennedy Institute of Ethics Bioethics Blog.
\end{etaremune}

## Abstracts

\begin{etaremune}
\renewcommand\labelenumi{\bfseries\theenumi .}
 \item \textbf{Getz, L.J.}, Maxwell, K.L. (2022). The Best Defence is a Good Offence: Understanding Antiphage Defence in \textit{V. parahaemolyticus} for more Effective Phage Therapy. 2022 QAtCanSTEM Colloquium, Halifax, NS. - October 2022
 \item \textbf{Getz, L.J.}, Brown, J.M., Sobot, L., Chow, A., Mahendrarajah, J., Thomas, N.A. (2021). DNA Cruciforms Regulate Virulence in Pathogenic \textit{Vibrio} Species. 70th Annual Conference of the Canadian Society of Microbiologists, Remote - June 2021.
 \item \textbf{Getz, L.J.}, Thomas. N.A. (2020). Functional genomics of \textit{Vibrio} pathogenesis and environmental persistence. 2020 Canadian Student Health Research Forum.
 \item \textbf{Getz, L.J.}, Brown, J., Thomas, N.A. (2019). Type III Secretion System Gene Expression and Virulence is Regulated by a DNA Cruciform Structure at the \textit{exsA} promoter in \textit{Vibrio parahaemolyticus}, Genomes to Biology: the 8th International Conference on the Biology of Vibrios, McGill University, Montreal, QC. - November 2019
 \item \textbf{Getz, L.J.}, Brown, J., Thomas, N.A. (2019). A DNA junction superstructure regulates Type III Secretion System gene expression and virulence in \textit{Vibrio parahaemolyticus}, The 69th Annual Conference of the Canadian Society of Microbiologists, Université de Sherbrooke, Sherbrooke, QC. - June 2019
 \item \textbf{Getz, L.J.}, Thomas, N.A. (2018). Flipping the Switch on Bacterial Pathogenesis: How the Leading Cause of Seafood-borne Gastroenteritis - \textit{Vibrio parahaemolyticus} - Regulates Virulence, LGBTSTEMinar 2019, Institute of Physics, London, UK. - January 2019
 \item \textbf{Getz, L.J.}, Comeau, A., Langille, M.G.I., Thomas, N.A. (2018). Linking Phenotype and Pathogen Genomics: Tn-Seq and Next Generation DNA Sequencing, PREP Graduate Student Research Day, Dalhousie University, Halifax, NS. - May 2018
 \item \textbf{Getz, L.J.}, Comeau, A., Langille, M.G.I., Thomas, N.A. (2018). Linking Phenotype and Pathogen Genomics: Tn-Seq and Next Generation DNA Sequencing, 23rd Annual Infectious Disease Research Day, Dalhousie University, Halifax, NS. - Apr 2018
 \item \textbf{Getz, L.J.}, Thomas, N.A. (2017). HlyU and H-NS Act as a Genetic Switch for Transcriptional Control of the Type III Secretion System-I Master Regulator \textit{exsA}, ASM Vibrio2017: The Biology of \textit{Vibrios}, Chicago, IL. - November 2017
 \item \textbf{Getz, L.J.}, Thomas, N.A. (2017). Discovery of a Genetic Switch in {Vibrio parahaemolyticus} That Contributes to Host Cell Death During Infection, 22nd Annual Infectious Disease Research Day, Dalhousie University, Halifax, NS. - March 2017
 \item \textbf{Getz, L.J.}, Finlayson-Trick, E.C.L., Hagar, M. Slaine, P.D., Thornbury, M., Lamourerux, E., Cook, J., Langille, M.G.I., Murray, L.E., McCormick, C., Rohde, J.R., Cheng, Z.A ‘spike’ in biofuel production: mining the porcupine microbiome to engineer a softwood feedstock platform, Giant Jamboree Abstract Guide, iGEM Giant Jamboree, Boston, MA. - October 2016
\end{etaremune}

# Conference Presentations

## Invited Talks

\begin{etaremune}
\renewcommand\labelenumi{\bfseries\theenumi .}
 \item \textbf{2022 Armand Frappier Outstanding Graduate Student Award Talk} - Attenuation of DNA Cruciform Structures by a Conserved Regulator Directs VIrulence Gene Expression in Pandemic \textit{Vibrio}. University of Guelph, Guelph, ON. June 2022.
 \item \textbf{2022 Al Downe Memorial Lecture} - Editing Nature: Genetically Modified Mosquitoes and a Case for Slow Science - Queen's University, Kingston, ON. March 2022.
 \item Transposon Sequencing: Functional Genomics for Probing Bacterial Pathogenesis. Genomics in Medicine - Emerging Technologies and Bioinformatic Challenges, Dalhousie University, Halifax, NS. Invited Talk. December 2019.
 \item \textit{Vibrio parahaemolyticus} and infection: A complex relationship between environment and host. Graduate Student Research Day Excellence in Research Award, Dalhousie University, Halifax, NS. Keynote. May 2019
 \item The Multimodel Lifestyle of Marine \textit{Vibrio}. Natural History Museum Life Science Seminar Series, Natural History Museum, London, UK. January 2019
\end{etaremune}

## Conference Talks
1. DNA Cruciforms Regulate Virulence Gene Expression in Pathogenic *Vibrio* Species. 70th Annual Conference of the Canadian Society of Microbiologists - Remote. June 2021.

2. Build Back Better: The Chief Science Advisor’s Youth Council’s Roundtables to Envision A Post-Pandemic Future in the Canadian Science Community. Canadian Science Policy Conference, University of Ottawa, Ottawa, QC. October 2020.

3. Functional genomics of *Vibrio* pathogenesis and environmental persistence. Canadian Student Health Research Forum, University of Manitoba, Regina, MB. August 2020.

4. A DNA Cruciform Structure Regulates Virulence Gene Expression in Human Pathogenic *Vibrio* species. PREP Graduate Student Research Day, Dalhousie University, Halifax, NS. June 2020.

5. A Regulator of Sugar Metabolism Implicated in the Secretion and Virulence of *Vibrio parahaemolyticus*. Professional Research and Education Program Graduate Student Research Day, Dalhousie University, Halifax, NS. May 2019

6. Type III Secretion System Gene Expression and Virulence is Regulated by a DNA Cruciform Structure at the *exsA* promoter in *Vibrio parahaemolyticus*. Genomes to Biology: The 8th International Conference on the Biology of *Vibrios*, McGill University, Montreal, QC. November 2019.

7. Creating LGBTQ+ Inclusive Spaces for Equitable Active Learning. Dalhousie Conference on University Teaching and Learning, Dalhousie University, Halifax, NS. May 2019

8. The Multimodal Lifestyle of Marine *Vibrios*. Microbiology and Immunology Seminar Series, Dalhousie University, Halifax, NS. January 2019

9. Flipping the Switch on Bacterial Pathogenesis: How the Leading Cause of Seafood-borne Gastroenteritis - *Vibrio parahaemolyticus* - Regulates Virulence. LGBTSTEMinar 2019, Institute of Physics, London, UK January 2019

10. Linking Phenotype and Pathogen Genomics: TnSeq and Next Generation DNA Sequencing. PREP Graduate Student Research Day, Dalhousie University, Halifax, NS. May 2018

11. *Vibrio parahaemolyticus*: A Versatile Pathogen Living a Dual-Lifestyle. Microbiology and Immunology Graduate Student Seminar, Dalhousie University, Halifax, NS. February 2018

12. Biofuel Production set to Spike: Identification of Biofuel Producing Enzymes in the Porcupine Microbiome. 2016 iGEM Giant Jamboree, iGEM, Boston, MA. October, 2016

# Conference Poster Presentations
> Poster Presenter**^\*^**

1. **Getz, L.J.**, Brown, J.M., Thomas, N.A.^\*^. A DNA junction superstructure regulates Type III Secretion System gene expression and virulence in *Vibrio parahaemolyticus*. 69th Annual Conference of the Canadian Society of Microbiologists, Université de Sherbrooke, Montreal, QC. June 2019

2. **Getz, L.J.**^\*^, Brown, J.M., Thomas, N.A. Type III Secretion System Gene Expression and Virulence is Regulated by a DNA Cruciform Structure at the *exsA promoter* in *Vibrio parahaemolyticus*. Centre for Comparative Genomics and Evolutionary Bioinformatics Research Retreat, Dalhousie University, Halifax, NS. November 2019

3. **Getz, L.J.**^\*^, Thomas, N.A. "Discovery of a Genetic Switch in *Vibrio parahaemolyticus* that Contributes to Host Cell Death during Infection."

4. **Getz, L.J.**^\*^, Comeau, A., Langille, M.G.I., Thomas, N.A. Linking Phenotype and Pathogen Genomics: TnSeq and Next Generation DNA Sequencing. 23rd Annual Infectious Disease Research Day, Centre for Vaccinology, Halifax, NS. April 2018

6. **Getz, L.J.**^\*^, Thomas, N.A. HlyU and H-NS act as a Genetic Switch for Transcriptional Control of the Type-III Secretion System I Master Regulator *exsA*. ASM Vibrio2017, American Society of Microbiology, Chicago, IL. November 2017.

7. **Getz, L.J.**^\*^, Thomas, N.A. Discovery of a Genetic Switch in *Vibrio parahaemolyticus* that Contributes to Host Cell Death during Infection. 22nd Annual Infectious Disease Research Day, Dalhousie University, Halifax, NS. April, 2017

8. **Getz, L.J.**^\*^, Finlayson-Trick, E.C.L.^\*^, Hagar, M.^\*^, Slaine, P.D., Thornbury, M., Lamourerux, E., Cook, J., Langille, M.G.I., Murray, L.E., McCormick, C., Rohde, J.R., Cheng, Z. Biofuel Production set to Spike: Identification of Biofuel Producing Enzymes in the Porcupine Microbiome 2016 iGEM Giant Jamboree, iGEM, Boston, MA. October 2016

# Grants

*Awareness and understanding of apheresis plasma donation and effectiveness of alternative donor screening questions for diverse gbMSM and trans populations*, Canadian Blood Services.

> Role: Collaborator under Dr. Jacqueline Gahagan

> Total award: $200,500

> Focus on plasma donation and policies surrounding LGBTQ+ donors.

# Teaching and Course-Design Experience

## Teaching Philosophy

>>>*“The ultimate goal of farming is not the growing of crops, but the cultivation and perfection of human beings.”*

>>>>**- Masanobu Fukuoka, Farmer and Philosopher**

>As an educator, I consider teaching to be like farming. As settlers, both sides of my family have farmed land in Canada they moved onto as part of the colonization of The West. Reflecting on this profession and on my family’s experiences has given me significant guidance in my teaching career thus far. In line with how Mr. Fukuoka understands the goals of farming, I believe that education’s ultimate goal is the cultivation and perfection of human beings.
>With that in mind, my teaching philosophy broadly covers three areas:

>> **Nuturing Students to grow,** $\\$
>> **Fostering Diversity and Inclusivity,** and $\\$
>> **Building Social Good through Education** $\\$

>For a complete teaching philosophy, please visit: [http://landongetz.com](http://landongetz.com) $\\$

## Courses
Part Time Academic, BIOL 3037: Life Rewritten \hfill Winter 2022 $\\$
*Dalhousie University*

> Shared instruction duties for the course with Dr. Patrice Cote, including preparing materials, lecturing, and marking examinable materials.

Course Developer, MICI2100DE \hfill Winter 2021 $\\$
*Dalhousie University*

> Redesigned online introductory microbiology course to include new material and more active learning activities, with less reliance on exam grades. 150-200 Students.

Online Module Developer, CHEM 1011/1021 and CHEM 1012/1022 \hfill June 2020 $\\$
*Dalhousie University*

> Redesigned the orbital hybridization online module, wrote scripts for video recordings, and built powerpoint lecture slides. 1000-1300 Students

Course-Designer & Teaching Assistant, BIOL3037: Life Rewritten \hfill Winter 2020/Winter 2021 $\\$
*Dalhousie University*

> Developed ethics portion of this new course, and lectured these portions to students. Built exam and assignment material. ~50 Students.

Part Time Academic, CHEM 1011/1021 and CHEM 1012/1022 \hfill Fall/Winter 2018/2019 $\\$
*Dalhousie University*

> Lecture support for CHEM 1011/1021 and CHEM 1012/1022. Lectured periodically and organized the strcuture, schedule, and TAs for the student-taught Chemistry Resource Centre. 1000-1300 Students.

Graduate Student Mentor, Dalhousie international Genetically Engineered Machine (iGEM) \hfill Summer/Fall 2018 $\\$
*Dalhousie University*

> Provided expertise of the iGEM competition and helped undergraduate students perform experiments and analysis.

Senior Chemistry Resource Centre Assistant, CHEM 1011/1021 and CHEM 1012/1022 \hfill Winter 2017 - Fall 2018 $\\$
*Dalhousie University*

> Organized the TAs and their schedule for the Chemistry Resource Centre. Provided additional lecture support for students through the resource centre.

Teaching Assistant, MICI 2100 \hfill Fall 2017 $\\$
*Dalhousie University*

> Provided additional resources for students, was an initial first contact for questions, and marked exams.

Bioinformatics and Web Design Mentor, Dalhousie iGEM \hfill Summer 2017 $\\$
*Dalhousie University*

> Utilized my bioinformatics and web design expertise to instruct the  undergraduate iGEM students in performing experiments and analysis, and documenting it online.

Chemistry Resource Centre Assistant, CHEM 1011/1021 and CHEM 1012/1022 \hfill Fall 2015 - Fall 2016 $\\$
*Dalhousie University*

> Provided additional lecture support for CHEM 1011/1021 and CHEM 1012/1022 students in the Chemistry Resource Centre.

## Laboratory Supervision Summary:

> Honours Students Supervised: 3 $\\$
> Summer Students Supervised: 8 $\\$
> Experiential Learning Students Supervised: 4
$\\$

# Awards

2022 Design2Learn (D2L) Innovation Award in Teaching and Learning - STLHE \hfill $3000 CAD Award to Team

2022 Armand-Frappier Outstanding Graduate Student Award - Canadian Society of Microbiologists \hfill $500 CAD Award

2021 Canadian College of Microbiologists Symposium Award -  70th Annual Conference of the CSM \hfill $500 CAD Award

2021 Educational Leadership Award for Collaborative Teaching - Dalhousie Centre for Learning and Teaching

2020 CIHR Silver Award - Canadian Student Health Research Forum \hfill $250 CAD Award

Nominated for: Dalhousie Impact Awards 2020: Outstanding Student of Distinction \hfill Not Awarded

Nominated for: 2020 Dalhousie's Board of Governors Award \hfill Not Awarded

People's Choice Award at the 8th Internation Conference on the Biology of Vibrios \hfill $200 CAD Award

**2019 President's Graduate Student Teaching Assistant Award** \hfill $500 CAD Award

2019 PREP Graduate Student Research Day Platform Presentation Award \hfill $200 CAD Award

2019 Faculty of Medicine Excellence in Research Award \hfill $1000 CAD Award

**2018/2019 Vanier Canadian Graduate Scholarship**  \hfill $150,000 CAD Award

**2019 Killam Graduate Scholarship** \hfill $90,000 CAD Award

**2019 Dalhouise University Faculty of Medicine Excellence in Research Award** \hfill $1,000 CAD Prize

2019 Alexander Graham Bell Canadian Graduate Scholarship - Honourary Doctoral Recipient \hfill $35,000 CAD Award

HHMI Tuition Scholarship, Cold Spring Harbor Laboratories Advanced Bacterial Genetics \hfill $1500 USD Award

2018 Nova Scotia Health Research Foundation Scotia Scholars Award \hfill $10,000 CAD Award

2018 Alexander Graham Bell Canadian Graduate Scholarship - Masters Recipient \hfill $17,500 CAD Award

2018 Nova Scotia Graduate Scholarship \hfill $10,000 CAD Award

2017 Award for Excellence in Undergraduate Honours Research \hfill $100 CAD Award

2017 Nova Scotia Graduate Scholarship \hfill $10,000 CAD Award

2017 Faculty of Science Undergraduate Research Prize

2017 Honours Student Prize \hfill $100 CAD Award

2016/2017 Academic Year – Faculty of Science Dean’s List

2016 NSERC University Summer Research Award \hfill $6,000 CAD Award

2015/2016 Academic Year – Faculty of Science Dean’s List

2015 Dalhousie University In-Course Scholarship \hfill $250 CAD Award

2014/2015 Academic Year – Faculty of Science Dean’s List

2013 Fall – Faculty of Science Dean’s List

2013 Dalhousie University Entrance Scholarship \hfill $750 CAD Award

2013 Alexander Rutherford Scholarship \hfill $2,500 CAD Award

# Professional Activities

## Government
Participant, Chief Science Advisor of Canada's Open Science Dialogues \hfill 2021 $\\$
*Office of the Chief Sciece Advisor, Government of Canada*

Observer, Expert Advisory Committee on COVID-19: Zoonosis \hfill 2020 $\\$
*Office of the Chief Science Advisor, Government of Canada*

Member, Chief Science Advisor's Youth Council \hfill 2019 - *Present* $\\$
*Office of the Chief Science Advisor, Government of Canada*

Consultant, CIHR Self-Identification Questionnaire Review \hfill 2019 - 2020 $\\$
*Canadian Institute of Health Research*

## Institutional
Participant, NSERC 2030: A Strategic Plan \hfill 2021 $\\$
*National Science and Engineering Research Council of Canada*

Graduate Student Representative, [Institute for Comparative Genomics](https://icgenomics.ca) \hfill 2021 - *Present* $\\$
*Dalhousie University*

Organizing Committee Member, CCfV/ID Research Day \hfill 2021 - *Present* $\\$
*Dalhousie University*

Network Member, [Editing Nature](https://www.editingnature.org/whoweare) \hfill 2019 - *Present* $\\$
*Yale University, New Haven, Connecticut*

Graduate Student Representative, Undergraduate Studies Committee, \hfill 2017 - 2019$\\$
*Department of Microbiology and Immunology, Dalhousie University*

Observer, NSHRF Peer-Review Panel \hfill 2018 $\\$
*Dalhousie University*

## Scientific Society Membership and Service
ASM Young Ambassador to Canada, American Society of Microbiology \hfill 2022

Student Member, Canadian Society of Micobiologists \hfill 2021 - *Present*

Student Member, American Society for Microbiology \hfill 2017 - *Present*

Student Member, Nova Scotia Institute of Science \hfill 2017 - *Present*

# Scientific Peer Review

- Biochemistry and Cell Biology (x1)
- mSystems (x3)
- Microbiome (x2)

# Community Activities
Board Member, Board of Directors \hfill 2019 - 2021 $\\$
*Scientists of the Maritimes*

Founder \hfill 2019 - *Present* $\\$
*Queer Atlantic Canadian Science, Technology, Engineering, and Mathematics (QAtCanSTEM)*

Primary Organizer, QAtCanSTEM Colloquium \hfill 2020 $\\$
 *Dalhousie University*

Front of House Volunteer \hfill 2013 - 2017 $\\$
*Halifax Music Co-op*

# Knowledge Translation and Media

**Dal News.** Making science a better place: Student‑led group expands efforts to create community for LGBTQ+ in STEM. August 18, 2021.$\\$
**Dal News.** EXCELLENCE IN EDUCATION: MEET THIS YEAR'S DALHOUSIE TEACHING AWARD WINNERS. June 23, 2021. $\\$
**Scientists in School.** Spotlight with Scientists in School: Landon Getz, Award Winning Post-Secondary Educator. March 1, 2021. $\\$
**Simcoe Reformer.** Why deliberately infecting healthy young volunteers with COVID-19 virus can be done ethically. October 22, 2020. $\\$
**CBC News.** How microbes could help clean up Nova Scotia's abandoned mines. August 6th, 2020.$\\$
**980 CKNW - The Jill Bennet Show.** Conversation on cornonavirus vaccines and treatments. April 23rd, 2020$\\$
**570 NEWS: Kitchener Today with Brian Bourke.** Conversation on cornonavirus vaccines and treatments. April 16th, 2020. $\\$
**Dal News.** CREATING A DEEPER SENSE OF COMMUNITY FOR LGBTQ+ SCIENTISTS. January 30th, 2020.
**The Signal.** Halifax event connects queer voices in STEM. January 20th, 2020. $\\$
**CBC Nova Scotia's Information Morning Radio Show.** QAtCanSTEM Colloquium: Being Queer in STEM. January 17th, 2020. $\\$
**Halifax's The Coast.** A first-of-its-kind queer STEM conference is in Halifax this weekend. January 16th, 2020.$\\$
**The National Post.** Breakthrough or a threat? Research on genetics of same-sex behaviour ignites ethical debate. December 6th, 2019.$\\$
**HalifaxToday.ca.** Halifax-based group building queer community in STEM fields. November 24th, 2019.$\\$
**The Sheldon McLeod Show.** QAtCanSTEM and Being a Queer Scientist. November 22nd, 2019.$\\$
**Dal News.** PRIDE IN STEM. July 25th, 2019.$\\$
**Dal News.** TEACHERS WHO INSPIRE: MEET THIS YEAR'S RECIPIENTS OF DAL'S UNIVERSITY‑WIDE TEACHING AWARDS. June 20th, 2019.$\\$
**Current Exchange: A blog by CSHL Meetings and Courses.** Visitor of the Week: Landon Getz. June 14th, 2019.$\\$
**Dal News.** GOVERNMENT OF CANADA SELECTS DAL PHDS AND POSTDOCS FOR ITS MOST ESTEEMED AWARDS. May 16th, 2019.$\\$
**CBC Nova Scotia's Information Morning Radio Show.** On the Call for a Moratorium on Germline Genome Editing. Feburary 2019.$\\$
**The Dalhousie Gazette.** Urban Garden is one of Dalhousie’s hidden gems by Lauren Hazlewood. September 27th, 2019.$\\$
**CBC Nova Scotia's Information Morning Radio Show.** LGBTSTEMDAY: Inclusion and Diversity in STEM with Portia Clarke, live in studio. July 2018.$\\$
**Halifax's The Coast.** 10 urban gardens you need to know by Victoria Walton. August 3rd, 2017$\\$
