---
output:
  pdf_document:
    latex_engine: lualatex
#    template: /home/landongetz/Nextcloud/CV/CV-latex/LJG-latex-cv.tex

geometry: margin=1in

keywords: R Markdown, academic CV, template

fontfamily: roboto
#fontfamilyoptions:
fontsize: 10pt
linkcolor: blue
urlcolor: blue
---

# Publications
> Career Total: 8 $\\$
> 81 Citations; h-index: 6 (as per Google Scholar)

## Journal Articles

*Corresponding Author*^\#^ | *Equal Contribution^\*^ (ordered alphabetically)*

   1. **Getz, L.J.**^\*^, Kratzer, K.^\*^, Peterlini, T., Masson, J-Y., Dellaire, G^\#^. (2021). "Addressing the dark matter of gene therapy: technical and ethical barriers to clinical application." *Human Genetics.* DOI: [https://doi.org/10.1007/s00439-021-02272-5](https://doi.org/10.1007/s00439-021-02272-5)

   2. **Getz, L.J.**, Dellaire, G.^\#^ (2020). "Back to Basics: Application of the 4-principle approach to bioethics to heritable genome editing." *Science and Engineering Ethics.* DOI: [https://doi.org/10.1007/s00439-021-02272-5](https://doi.org/10.1007/s11948-020-00226-0).

  3. **Getz, L. J.**, Runté, C., Rainey, J., Thomas, N.A.^\#^ (2019). "Tyrosine phosphorylation as a widespread regulatory mechanism in prokaryotes." *Journal of Bacteriology.* DOI: [https://doi.org/10.1128/JB.00205-19](https://doi.org/10.1128/JB.00205-19)

  4. Thornbury, M., Sicheri, J., Slaine, P.D., **Getz, L. J.**, Finlayson-Trick, E.C.L., Cook, J., Guinard, C., Boudreau, N., Jakeman, D., Rohde, J.R., McCormick, C.^\#^ (2018). "Characterization of novel lignocellulose-degrading enzymes from the porcupine microbiome using synthetic metagenomics" *PLoS One.* DOI: [https://doi.org/10.1371/journal.pone.0209221](https://doi.org/10.1371/journal.pone.0209221).


  5. **Getz, L.J.^\#^**, Dellaire, G.^\#^ (2018). "Angels and Devils: Dual-Use in Biotechnology." *Trends in Biotechnology.* DOI: [https://doi.org/10.1016/j.tibtech.2018.07.016](https://doi.org/10.1016/j.tibtech.2018.07.016).


  6. Runté, C., Jain, U., **Getz, L.J.**, Secord, S., Kuwae, A., Abe, A., Leblanc, J., Stadnyk, A.W., Kaper, J.B., Hansen, A.M., Thomas, N.A.^\#^ (2018). "Tandem tyrosine phosphosites in the enteropathogenic *Escherichia coli* chaperone CesT are required for differential type III effector translocation and virulence." *Molecular Microbiology.* DOI: [https://doi.org/10.1111/mmi.13948](https://doi.org/10.1111/mmi.13948).


  7. **Getz, L.J.**, Thomas, N.A.^\#^ (2018) "The Transcriptional Regulator HlyU is a Positive Regulator for Expression of *exsA* Leading to Type III Secretion System-1 Activation in *Vibrio parahaemolyticus*" *Journal of Bacteriology.* DOI: [https://doi.org/10.1128/JB.00653-17](https://doi.org/10.1128/JB.00653-17).

  8. **Getz, L.J.**^\*^, Finlayson-Trick, E.C.L.^\*^, Slaine, P.D.^\*^, Thornbury, M., Lamourerux, E., Cook, J., Langille, M.G.I., Murray, L.E., McCormick, C., Rohde, J.R., Cheng, Z.^\#^ (2017). "Taxonomic differences of gut microbiomes drive cellulolytic enzymatic potential within hind-gut fermenting mammals." *PLoS One.* DOI: [https://doi.org/10.1371/journal.pone.0189404](https://doi.org/10.1371/journal.pone.0189404).

### In Preparation

  9. **Getz, L.J.**, Brown, J.M., Sobot, L., Chow, A., Mahendrarajah, J., Thomas, N.A.^\#^. (2021). Resolution of DNA Cruciforms by a Conserved Regulator Directs Virulence in Pandemic *Vibrio*. Submitted to Nature Microbiology.

## Theses

  10. **Getz, L.J.** (2017) "A Genetic Switch Controls the Type III Secretion System Master Regulator, ExsA, in *Vibrio parahaemolyticus* RIMD2210633". *B.Sc (Hons).* Dalhousie University, Halifax, NS, Canada.

  11. **Getz, L.J.** (In Preparation) "Whole Genome Interrogation of *Vibrio parahaemolyticus* RIMD2210633 Metabolism and Virulence Gene Regulons". *Ph.D.* Dalhousie University, Halifax, NS, Canada.

## Abstracts

  1. **Getz, L.J.**, Brown, J.M., Sobot, L., Chow, A., Mahendrarajah, J., Thomas, N.A. (2021). DNA Cruciforms Regulate Virulence in Pathogenic *Vibrio* Species. 70th Annual Conference of the Canadian Society of Microbiologists, Remote - June 2021.

  2. **Getz, L.J.**, Thomas. N.A. (2020). Functional genomics of Vibrio pathogenesis and environmental persistence. 2020 Canadian Student Health Research Forum.

  3. **Getz, L.J.**, Brown, J., Thomas, N.A. (2019). Type III Secretion System Gene Expression and Virulence is Regulated by a DNA Cruciform Structure at the exsA promoter in Vibrio parahaemolyticus, Genomes to Biology: the 8th International Conference on the Biology of Vibrios, McGill University, Montreal, QC. - November 2019

  4. **Getz, L.J.**, Brown, J., Thomas, N.A. (2019). A DNA junction superstructure regulates Type III Secretion System gene expression and virulence in Vibrio parahaemolyticus, The 69th Annual Conference of the Canadian Society of Microbiologists, Université de Sherbrooke, Sherbrooke, QC. - June 2019

  5. **Getz, L.J.**, Thomas, N.A. (2018). Flipping the Switch on Bacterial Pathogenesis: How the Leading Cause of Seafood-borne Gastroenteritis - Vibrio parahaemolyticus - Regulates Virulence, LGBTSTEMinar 2019, Institute of Physics, London, UK. - January 2019

  6. **Getz, L.J.**, Comeau, A., Langille, M.G.I., Thomas, N.A. (2018). Linking Phenotype and Pathogen Genomics: Tn-Seq and Next Generation DNA Sequencing, PREP Graduate Student Research Day, Dalhousie University, Halifax, NS. - May 2018

  7. **Getz, L.J.**, Comeau, A., Langille, M.G.I., Thomas, N.A. (2018). Linking Phenotype and Pathogen Genomics: Tn-Seq and Next Generation DNA Sequencing, 23rd Annual Infectious Disesase Research Day, Dalhousie University, Halifax, NS. - Apr 2018

  8. **Getz, L.J.**, Thomas, N.A. (2017). HlyU and H-NS Act as a Genetic Switch for Transcriptional Control of the Type III Secretion System-I Master Regulator exsA, ASM Vibrio2017: The Biology of Vibrios, Chicago, IL. - November 2017

  9. **Getz, L.J.**, Thomas, N.A. (2017). Discovery of a Genetic Switch in Vibrio parahaemolyticus That Contributes to Host Cell Death During Infection, 22nd Annual Infectious Disease Research Day, Dalhousie University, Halifax, NS. - March 2017

  10. **Getz, L.J.**, Finlayson-Trick, E.C.L., Hagar, M. Slaine, P.D., Thornbury, M., Lamourerux, E., Cook, J., Langille, M.G.I., Murray, L.E., McCormick, C., Rohde, J.R., Cheng, Z.A ‘spike’ in biofuel production: mining the porcupine microbiome to engineer a softwood feedstock platform, Giant Jamboree Abstract Guide, iGEM Giant Jamboree, Boston, MA. - October 2016

# Commentary
1. Baylis, F., **Getz, L.J.** (2021). [Challenge studies for COVID-19: Now is still not the time.](https://blogs.bmj.com/medical-ethics/2021/04/27/challenge-studies-for-covid-19-now-is-still-not-the-time/) JME Blog

2. **Getz, L.J.**, Baylis, F. (2021). [Challenge studies for COVID-19: Now is not the time.](https://blogs.bmj.com/medical-ethics/2021/04/06/challenge-studies-for-covid-19-now-is-not-the-time/) JME Blog

3. **Getz, L.J.**, Baylis, F. (2020). [Canada should reject the idea of deliberately infecting vaccine volunteers.](https://policyoptions.irpp.org/magazines/november-2020/canada-should-reject-the-idea-of-deliberately-infecting-vaccine-volunteers/) PolicyOptions.ca.

4. Baylis, F., **Getz, L.J.** (2020). [Why federal government should reject human challenge trials for COVID-19 vaccine.](https://www.cbc.ca/news/opinion/opinion-covid-vaccine-human-challenge-trials-1.5790713) CBC Opinion.

5. Qaiser, F., Morriseau, T., Rilling, M., Cartile, A., Sung, M., **Getz, L.J.**, Boulanger, M-E. (2020). [Envisioning A Post-Pandemic Future in the Canadian Science Community: A Youth Perspective.](https://sciencepolicy.ca/posts/envisioning-a-post-pandemic-future-in-the-canadian-science-community-a-youth-perspective/) Canadian Science Policy Conference 2020.

6. Baylis, F., **Getz, L.J.** (2020). [Rush to risky chellenge trials is unethical.](https://healthydebate.ca/2020/10/topic/risky-challenge-trials-unethical/) HealthyDebate.ca.

7. **Getz, L.J.** (2020). [Rushing coronavirus vaccines and treatments could do more harm than good.](https://theconversation.com/rushing-coronavirus-vaccines-and-treatments-could-do-more-harm-than-good-136449) TheConversation.ca, Republished in Everything Zoomer, and Dal News.

8. Kofler, N., **Getz, L.J.**, Baylis, F., Dellaire, G. (2019). [Genetically modifying mosquitoes to control the spread of disease carries unknown risks.](https://theconversation.com/genetically-modifying-mosquitoes-to-control-the-spread-of-disease-carries-unknown-risks-123862) TheConversation.ca, republished in Salon, HalifaxToday.ca, SaltWire Newspapers, and Gannett Newspapers.

9. **Getz, L.J.**, Dellaire, G. (2019). [Moratorium on Human Genome Editing: Time to Get It Right.](https://www.thehastingscenter.org/moratorium-on-human-genome-editing-time-to-get-it-right/) The Hastings Center Forum Blog.

10. **Getz, L.J.**, Dellaire, G. (2019). [CRISPR gene editing: Why we need Slow Science.](https://theconversation.com/crispr-gene-editing-why-we-need-slow-science-113639) The Conversation.ca.

11. **Getz, L.J.** (2019). [The "Value" of Consumer DNA Sequencing.](https://impactethics.ca/2019/02/28/the-value-of-consumer-dna-sequencing/) Impact Ethics at Novel Tech Ethics.

12. **Getz, L.J.**, Dellaire, G., Baylis, F. (2018). [Jiankui He: A Sorry Tale of High-Stakes Science.](https://www.thehastingscenter.org/jiankui-sorry-tale-high-stakes-science/) The Hastings Center Forum Blog.

13. Baylis, F., Dellaire, G., **Getz, L.J.** (2018). [Why we are not ready for genetically designed babies.](https://theconversation.com/why-we-are-not-ready-for-genetically-designed-babies-107756) The Conversation.ca. Reprinted in: The National Post and the Halifax Chronicle Herald.

14. **Getz, L.J.** (2018). [Thicker Than Water: Slow Movement on Blood Policy.](https://impactethics.ca/2018/10/26/thicker-than-water-slow-movement-on-blood-policy/) Impact Ethics at Novel Tech Ethics.

15. **Getz, L.J.** (2018). [The Privacy Implications of Human DNA Sequencing.](https://impactethics.ca/2018/05/11/the-privacy-implications-of-human-dna-sequencing/) Impact Ethics at Novel Tech Ethics.

16. **Getz, L.J.** (2017). [A Reflection on Blood Donation Policy in Canada.](https://impactethics.ca/2017/08/24/a-reflection-on-blood-donation-policy-in-canada/) Impact Ethics at Novel Tech Ethics. Reprinted at the Kennedy Institute of Ethics Bioethics Blog.

# Invited Seminars and Talks

1. Transposon Sequencing: Functional Genomics for Probing Bacterial Pathogenesis. Genomics in Medicine - Emerging Technologies and Bioinformatic Challenges, Dalhousie University, Halifax, NS. Invited Talk. December 2019.

2. *Vibrio parahaemolyticus* and infection: A complex relationship between environment and host. Graduate Student Research Day Excellence in Research Award, Dalhousie University, Halifax, NS. Keynote. May 2019

3. The Multimodel Lifestyle of Marine *Vibrio*. Natural History Museum Life Science Seminar Series, Natural History Museum, London, UK. January 2019

# Conference Talks
1. DNA Cruciforms Regulate Virulence Gene Expression in Pathogenic *Vibrio* Species. 70th Annual Conference of the Canadian Society of Microbiologists - Remote. June 2021.

2. Build Back Better: The Chief Science Advisor’s Youth Council’s Roundtables to Envision A Post-Pandemic Future in the Canadian Science Community. Canadian Science Policy Conference, University of Ottawa, Ottawa, QC. October 2020.

3. Functional genomics of *Vibrio* pathogenesis and environmental persistence. Canadian Student Health Research Forum, University of Manitoba, Regina, MB. August 2020.

4. A DNA Cruciform Structure Regulates Virulence Gene Expression in Human Pathogenic *Vibrio* species. PREP Graduate Student Research Day, Dalhousie University, Halifax, NS. June 2020.

5. A Regulator of Sugar Metabolism Implicated in the Secretion and Virulence of *Vibrio parahaemolyticus*. Professional Research and Education Program Graduate Student Research Day, Dalhousie University, Halifax, NS. May 2019

6. Type III Secretion System Gene Expression and Virulence is Regulated by a DNA Cruciform Structure at the *exsA* promoter in *Vibrio parahaemolyticus*. Genomes to Biology: The 8th International Conference on the Biology of *Vibrios*, McGill University, Montreal, QC. November 2019.

7. Creating LGBTQ+ Inclusive Spaces for Equitable Active Learning. Dalhousie Conference on University Teaching and Learning, Dalhousie University, Halifax, NS. May 2019

8. The Multimodal Lifestyle of Marine *Vibrios*. Microbiology and Immunology Seminar Series, Dalhousie University, Halifax, NS. January 2019

9. Flipping the Switch on Bacterial Pathogenesis: How the Leading Cause of Seafood-borne Gastroenteritis - *Vibrio parahaemolyticus* - Regulates Virulence. LGBTSTEMinar 2019, Institute of Physics, London, UK January 2019

10. Linking Phenotype and Pathogen Genomics: TnSeq and Next Generation DNA Sequencing. PREP Graduate Student Research Day, Dalhousie University, Halifax, NS. May 2018

11. *Vibrio parahaemolyticus*: A Versatile Pathogen Living a Dual-Lifestyle. Microbiology and Immunology Graduate Student Seminar, Dalhousie University, Halifax, NS. February 2018

12. Biofuel Production set to Spike: Identification of Biofuel Producing Enzymes in the Porcupine Microbiome. 2016 iGEM Giant Jamboree, iGEM, Boston, MA. October, 2016

# Conference Poster Presentations
> Poster Presenter**^\*^**

1. **Getz, L.J.**, Brown, J.M., Thomas, N.A.^\*^. A DNA junction superstructure regulates Type III Secretion System gene expression and virulence in *Vibrio parahaemolyticus*. 69th Annual Conference of the Canadian Society of Microbiologists, Université de Sherbrooke, Montreal, QC. June 2019

2. **Getz, L.J.**^\*^, Brown, J.M., Thomas, N.A. Type III Secretion System Gene Expression and Virulence is Regulated by a DNA Cruciform Structure at the *exsA promoter* in *Vibrio parahaemolyticus*. Centre for Comparative Genomics and Evolutionary Bioinformatics Research Retreat, Dalhousie University, Halifax, NS. November 2019

3. **Getz, L.J.**^\*^, Thomas, N.A. "Discovery of a Genetic Switch in *Vibrio parahaemolyticus* that Contributes to Host Cell Death during Infection."

4. **Getz, L.J.**^\*^, Comeau, A., Langille, M.G.I., Thomas, N.A. Linking Phenotype and Pathogen Genomics: TnSeq and Next Generation DNA Sequencing. 23rd Annual Infectious Disease Research Day, Centre for Vaccinology, Halifax, NS. April 2018

6. **Getz, L.J.**^\*^, Thomas, N.A. HlyU and H-NS act as a Genetic Switch for Transcriptional Control of the Type-III Secretion System I Master Regulator *exsA*. ASM Vibrio2017, American Society of Microbiology, Chicago, IL. November 2017.

7. **Getz, L.J.**^\*^, Thomas, N.A. Discovery of a Genetic Switch in *Vibrio parahaemolyticus* that Contributes to Host Cell Death during Infection. 22nd Annual Infectious Disease Research Day, Dalhousie University, Halifax, NS. April, 2017

8. **Getz, L.J.**^\*^, Finlayson-Trick, E.C.L.^\*^, Hagar, M.^\*^, Slaine, P.D., Thornbury, M., Lamourerux, E., Cook, J., Langille, M.G.I., Murray, L.E., McCormick, C., Rohde, J.R., Cheng, Z. Biofuel Production set to Spike: Identification of Biofuel Producing Enzymes in the Porcupine Microbiome 2016 iGEM Giant Jamboree, iGEM, Boston, MA. October 2016

# Knowledge Translation and Media

**Dal News.** Making science a better place: Student‑led group expands efforts to create community for LGBTQ+ in STEM. August 18, 2021.$\\$
**Dal News.** EXCELLENCE IN EDUCATION: MEET THIS YEAR'S DALHOUSIE TEACHING AWARD WINNERS. June 23, 2021. $\\$
**Scientists in School.** Spotlight with Scientists in School: Landon Getz, Award Winning Post-Secondary Educator. March 1, 2021. $\\$
**Simcoe Reformer.** Why deliberately infecting healthy young volunteers with COVID-19 virus can be done ethically. October 22, 2020. $\\$
**CBC News.** How microbes could help clean up Nova Scotia's abandoned mines. August 6th, 2020.$\\$
**980 CKNW - The Jill Bennet Show.** Conversation on cornonavirus vaccines and treatments. April 23rd, 2020$\\$
**570 NEWS: Kitchener Today with Brian Bourke.** Conversation on cornonavirus vaccines and treatments. April 16th, 2020. $\\$
**Dal News.** CREATING A DEEPER SENSE OF COMMUNITY FOR LGBTQ+ SCIENTISTS. January 30th, 2020.
**The Signal.** Halifax event connects queer voices in STEM. January 20th, 2020. $\\$
**CBC Nova Scotia's Information Morning Radio Show.** QAtCanSTEM Colloquium: Being Queer in STEM. January 17th, 2020. $\\$
**Halifax's The Coast.** A first-of-its-kind queer STEM conference is in Halifax this weekend. January 16th, 2020.$\\$
**The National Post.** Breakthrough or a threat? Research on genetics of same-sex behaviour ignites ethical debate. December 6th, 2019.$\\$
**HalifaxToday.ca.** Halifax-based group building queer community in STEM fields. November 24th, 2019.$\\$
**The Sheldon McLeod Show.** QAtCanSTEM and Being a Queer Scientist. November 22nd, 2019.$\\$
**Dal News.** PRIDE IN STEM. July 25th, 2019.$\\$
**Dal News.** TEACHERS WHO INSPIRE: MEET THIS YEAR'S RECIPIENTS OF DAL'S UNIVERSITY‑WIDE TEACHING AWARDS. June 20th, 2019.$\\$
**Current Exchange: A blog by CSHL Meetings and Courses.** Visitor of the Week: Landon Getz. June 14th, 2019.$\\$
**Dal News.** GOVERNMENT OF CANADA SELECTS DAL PHDS AND POSTDOCS FOR ITS MOST ESTEEMED AWARDS. May 16th, 2019.$\\$
**CBC Nova Scotia's Information Morning Radio Show.** On the Call for a Moratorium on Germline Genome Editing. Feburary 2019.$\\$
**The Dalhousie Gazette.** Urban Garden is one of Dalhousie’s hidden gems by Lauren Hazlewood. September 27th, 2019.$\\$
**CBC Nova Scotia's Information Morning Radio Show.** LGBTSTEMDAY: Inclusion and Diversity in STEM with Portia Clarke, live in studio. July 2018.$\\$
**Halifax's The Coast.** 10 urban gardens you need to know by Victoria Walton. August 3rd, 2017$\\$
