---
output:
  pdf_document:
    latex_engine: lualatex
    template: /home/landongetz/Documents/CV/LJG-latex-cv.tex

geometry: margin=0.75in

title: "CV"
author: Landon J. Getz

jobtitle: "PhD Candidate"
address: "Department of Microbiology & Immunology - Dalhousie University"
address2: "5850 College Street, Room 7-C, PO BOX 15000 Halifax, NS  B3H 4R2"
#fontawesome: yes
fontawesome5: yes
email: landon.getz@dal.ca
#github: landongetz
twitter: landongetz
orcid: "0000-0002-3841-1062"
#phone: "+353 1 408 4800"
web: landongetz.com
updated: no

keywords: R Markdown, academic CV, template

fontfamily: roboto
#fontfamilyoptions:
fontsize: 10pt
linkcolor: blue
urlcolor: blue
---
$\\$

Landon Getz is a Ph.D. Candidate in the Department of Microbiology and Immunology at Dalhousie University. Landon has a Bachelor of Science Honours degree as well as a Certificate in Genetics from Dalhousie University. He is a Vanier Scholar, Killam Laureate, and a member of the Chief Science Advisor's inaugural youth council. Landon is an award-winning educator, with a deep focus on enhancing equity, diversity, and inclusion in the classroom through Universal Design for Learning, and by recognizing the unique struggles of marginalized and underrepresented students.

Landon has a keen interest in understanding the microbial underpinnings of pathogenesis and the evolution of pathogenesis in environmental organisms. Through this interest, Landon explores the pathogenecity and environmental survival of *Vibrio parahaemolyticus* and the genetics of T3SS biogenesis in both *V. parahaemolyticus* and Enteropathogenic *E. coli*. Landon is also deeply interested in the intersections between science and society, and uses this interest to pursue the ethical and policy implications of new and emerging medical and genetic technologies, such as CRISPR/Cas9. Consequently, Landon has published several peer-reviewed journal articles and commentaries on both microbial genetics and pathogenesis, as well as bioethics.

# Education

*Faculty of Medicine, Dalhousie University*, Ph.D. in Microbiology & Immunology \hfill Enrolled

*Centre for Learning and Teaching, Dalhousie University*, Certificate in University Teaching and Learning \hfill Enrolled

> Completed CNLT5000, the Graduate Student Teaching course through the Centre for Learning and Teaching, as part of this certificate.

*Faculty of Science, Dalhousie University*, B.Sc. in Microbiology & Immunology \hfill 2017

>First Class Honours - cGPA > 3.7 $\\$
>Department of Microbiology and Immunology Honours Student Research Prize

*Faculty of Science, Dalhousie University*, Certificate in Genetics \hfill 2017

# Teaching and Course-Design Experience
## Teaching Philosophy


>>>*“The ultimate goal of farming is not the growing of crops, but the cultivation and perfection of human beings.”*

>>>>**- Masanobu Fukuoka, Farmer and Philosopher**


As an educator, I consider teaching to be like farming. As settlers, both sides of my family have farmed land in Canada they moved onto as part of the colonization of The West. Reflecting on this profession and on my family’s experiences has given me significant guidance in my teaching career thus far. In line with how Mr. Fukuoka understands the goals of farming, I believe that education’s ultimate goal is the cultivation and perfection of human beings.
With that in mind, my teaching philosophy broadly covers three areas:

> **Nuturing Students to Grow,** $\\$
> **Fostering Diversity and Inclusivity,** and $\\$
> **Building Social Good through Education**

For a complete teaching philosophy, please visit: [http://landongetz.com](http://landongetz.com)

## Courses

Course Developer, MICI2100DE \hfill Winter 2021 $\\$
*Dalhousie University*

> Redesigned online introductory microbiology course to include new material and more active learning activities, with less reliance on exam grades. 150-200 Students.

Online Module Developer, CHEM 1011/1021 and CHEM 1012/1022 \hfill June 2020 $\\$
*Dalhousie University*

> Redesigned the orbital hybridization online module, wrote scripts for video recordings, and built powerpoint lecture slides. 1000-1300 Students

Course-Designer & Teaching Assistant, BIOL3037: Life Rewritten \hfill Winter 2020/Winter 2021 $\\$
*Dalhousie University*

> Designed ethics portion of this new course, and lectured these portions to students. Built exam and assignment material. ~50 Students.

Part Time Academic, CHEM 1011/1021 and CHEM 1012/1022 \hfill Fall/Winter 2018/2019 $\\$
*Dalhousie University*

> Lecture support for CHEM 1011/1021 and CHEM 1012/1022. Lectured periodically and organized the strcuture, schedule, and TAs for the student-taught Chemistry Resource Centre. 1000-1300 Students.

Graduate Student Mentor, Dalhousie international Genetically Engineered Machine (iGEM) \hfill Summer/Fall 2018 $\\$
*Dalhousie University*

> Provided expertise of the iGEM competition and helped undergraduate students perform experiments and analysis.

Senior Chemistry Resource Centre Assistant, CHEM 1011/1021 and CHEM 1012/1022 \hfill Winter 2017 - Fall 2018 $\\$
*Dalhousie University*

> Organized the TAs and their schedule for the Chemistry Resource Centre. Provided additional lecture support for students through the resource centre.

Teaching Assistant, MICI 2100 \hfill Fall 2017 $\\$
*Dalhousie University*

> Provided additional resources for students, was an initial first contact for questions, and marked exams.

Bioinformatics and Web Design Mentor, Dalhousie iGEM \hfill Summer 2017 $\\$
*Dalhousie University*

> Utilized my bioinformatics and web design expertise to instruct the  undergraduate iGEM students in performing experiments and analysis, and documenting it online.

Chemistry Resource Centre Assistant, CHEM 1011/1021 and CHEM 1012/1022 \hfill Fall 2015 - Fall 2016 $\\$
*Dalhousie University*

> Provided additional lecture support for CHEM 1011/1021 and CHEM 1012/1022 students in the Chemistry Resource Centre.

## Laboratory Supervision Summary:

> Honours Students Supervised: 2 $\\$
> Summer Students Supervised: 8
$\\$

# Selected Knowledge Translation and Media

**Dal News.** [Creating a Deeper Sense of Community for LGBTQ+ Scientists](https://www.dal.ca/news/2020/01/30/creating-a-deeper-sense-of-community-for-lgbtq--scientists.html). January 30th, 2020.
$\\$
**The Signal.** [Halifax event connects queer voices in STEM](https://signalhfx.ca/halifax-event-connects-queer-voices-in-stem/). January 20th, 2020. $\\$
**CBC Nova Scotia's Information Morning Radio Show.** QAtCanSTEM Colloquium: Being Queer in STEM. January 17th, 2020. $\\$
**Halifax's The Coast.** [A first-of-its-kind queer STEM conference is in Halifax this weekend](https://www.thecoast.ca/halifax/a-first-of-its-kind-queer-stem-conference-is-in-halifax-this-weekend/Content?oid=23271491). January 16th, 2020.$\\$
**The National Post.** [Breakthrough or a threat? Research on genetics of same-sex behaviour ignites ethical debate](https://nationalpost.com/health/breakthrough-or-a-threat-research-on-genetics-of-same-sex-behaviour-ignites-ethical-debate). December 6th, 2019.$\\$
**HalifaxToday.ca.** [Halifax-based group building queer community in STEM fields](https://www.halifaxtoday.ca/local-news/halifax-based-group-building-queer-community-in-stem-fields-1879636). November 24th, 2019.$\\$
**The Sheldon McLeod Show.** QAtCanSTEM and Being a Queer Scientist. November 22nd, 2019.$\\$
**Dal News.** [Pride in STEM](https://www.dal.ca/news/2019/07/25/pride-in-stem.html). July 25th, 2019.$\\$

# Selected Awards

>Career Total: $326,750 $\\$

2020 CIHR Silver Award - Canadian Student Health Research Forum \hfill $250 CAD Award

People's Choice Award at the 8th Internation Conference on the Biology of Vibrios \hfill $200 CAD Award

**2019 President's Graduate Student Teaching Assistant Award** \hfill $500 CAD Award

2019 Faculty of Medicine Excellence in Research Award \hfill $1000 CAD Award

**2018/2019 Vanier Canadian Graduate Scholarship**  \hfill $150,000 CAD Award

**2019 Killam Graduate Scholarship** \hfill $90,000 CAD Award

2019 Dalhouise University Faculty of Medicine Excellence in Research Award \hfill $1,000 CAD Prize

2019 Alexander Graham Bell Canadian Graduate Scholarship - Honourary Doctoral Recipient \hfill $35,000 CAD Award

HHMI Tuition Scholarship, Cold Spring Harbor Laboratories Advanced Bacterial Genetics \hfill $1500 USD Award

2018 Nova Scotia Health Research Foundation Scotia Scholars Award \hfill $10,000 CAD Award

2018 Alexander Graham Bell Canadian Graduate Scholarship - Masters Recipient \hfill $17,500 CAD Award

2018 Nova Scotia Graduate Scholarship \hfill $10,000 CAD Award

2017 Award for Excellence in Undergraduate Honours Research \hfill $100 CAD Award

2017 Nova Scotia Graduate Scholarship \hfill $10,000 CAD Award

2017 Faculty of Science Undergraduate Research Prize

2017 Honours Student Prize \hfill $100 CAD Award

2016 NSERC University Summer Research Award \hfill $6,000 CAD Award

# Publications
> Career Total: 8 $\\$
> 43 Citations; h-index: 5 (as per Google Scholar)

## Journal Articles

*Corresponding Author*^\#^ | *Equal Contribution*^\*^

1. **Getz, L.J.**, Dellaire, G.^\#^ (2020). "Back to Basics: Application of the 4-principle approach to bioethics to heritable genome editing." Science and Engineering Ethics. [DOI: 10.1007/s11948-020-00226-0](https://doi.org/10.1007/s11948-020-00226-0).


2. **Getz, L. J.**, Runté, C., Rainey, J., Thomas, N.A.^\#^ (2019). "Tyrosine phosphorylation as a widespread regulatory mechanism in prokaryotes." Journal of Bacteriology. [DOI: 10.1128/JB.00205-19](https://doi.org/10.1128/JB.00205-19).

3. Thornbury, M., Sicheri, J., Slaine, P.D., **Getz, L. J.**, Finlayson-Trick, E.C.L., Cook, J., Guinard, C., Boudreau, N., Jakeman, D., Rohde, J.R., McCormick, C.^\#^ (2018). "Characterization of novel lignocellulose-degrading enzymes from the porcupine microbiome using synthetic metagenomics" PLoS One. [DOI: 10.1371/journal.pone.0209221](https://doi.org/10.1371/journal.pone.0209221).


4. **Getz, L.J.^\#^**, Dellaire, G.^\#^ (2018). "Angels and Devils: Dual-Use in Biotechnology." Trends in Biotechnology. [DOI: 10.1016/j.tibtech.2018.07.016](https://doi.org/10.1016/j.tibtech.2018.07.016).


5. Runté, C., Jain, U., **Getz, L.J.**, Secord, S., Kuwae, A., Abe, A., Leblanc, J., Stadnyk, A.W., Kaper, J.B., Hansen, A.M., Thomas, N.A.^\#^ (2018). "Tandem tyrosine phosphosites in the enteropathogenic *Escherichia coli* chaperone CesT are required for differential type III effector translocation and virulence." Molecular Microbiology. [DOI: 10.1111/mmi.13948](https://doi.org/10.1111/mmi.13948).


6. **Getz, L.J.**, Thomas, N.A.^\#^ (2018) "The Transcriptional Regulator HlyU is a Positive Regulator for Expression of exsA Leading to Type III Secretion System-1 Activation in *Vibrio parahaemolyticus*" Journal of Bacteriology. [DOI: 10.1128/JB.00653-17](https://doi.org/10.1128/JB.00653-17).


7. **Getz, L.J.**^\*^, Finlayson-Trick, E.C.L.^\*^, Slaine, P.D.^\*^, Thornbury, M., Lamourerux, E., Cook, J., Langille, M.G.I., Murray, L.E., McCormick, C., Rohde, J.R., Cheng, Z.^\#^ (2017). "Taxonomic differences of gut microbiomes drive cellulolytic enzymatic potential within hind-gut fermenting mammals." PLoS One. [DOI: 10.1371/journal.pone.0189404](https://doi.org/10.1371/journal.pone.0189404).

## Theses

8. **Getz, L.J.** (2017) "A Genetic Switch Controls the Type III Secretion System Master Regulator, ExsA, in *Vibrio parahaemolyticus* RIMD2210633". *B.Sc (Hons).* Dalhousie University, Halifax, NS, Canada.

# Selected Commentary

1. **Getz, L.J.**, Baylis, F. (2020). [Canada should reject the idea of deliberately infecting vaccine volunteers](https://policyoptions.irpp.org/magazines/november-2020/canada-should-reject-the-idea-of-deliberately-infecting-vaccine-volunteers/), PolicyOptions.ca.

2. Baylis, F., **Getz, L.J.** (2020). [Why federal government should reject human challenge trials for COVID-19 vaccine](https://www.cbc.ca/news/opinion/opinion-covid-vaccine-human-challenge-trials-1.5790713), CBC Opinion.

3. Qaiser, F., Morriseau, T., Rilling, M., Cartile, A., Sung, M., **Getz, L.J.**, Boulanger, M-E. (2020). [Envisioning A Post-Pandemic Future in the Canadian Science Community: A Youth Perspective](https://sciencepolicy.ca/posts/envisioning-a-post-pandemic-future-in-the-canadian-science-community-a-youth-perspective/), Canadian Science Policy Conference 2020.

5. **Getz, L.J.** (2020). [Rushing coronavirus vaccines and treatments could do more harm than good](https://theconversation.com/rushing-coronavirus-vaccines-and-treatments-could-do-more-harm-than-good-136449), TheConversation.ca, Republished in Everything Zoomer, and Dal News.

6. Kofler, N., **Getz, L.J.**, Baylis, F., Dellaire, G. (2019). [Genetically modifying mosquitoes to control the spread of disease carries unknown risks](https://theconversation.com/genetically-modifying-mosquitoes-to-control-the-spread-of-disease-carries-unknown-risks-123862), TheConversation.ca, republished in Salon, HalifaxToday.ca, SaltWire Newspapers, and Gannett Newspapers.

7. **Getz, L.J.**, Dellaire, G. (2019). [Moratorium on Human Genome Editing: Time to Get It Right](https://www.thehastingscenter.org/moratorium-on-human-genome-editing-time-to-get-it-right/), The Hastings Center Forum Blog.

8. **Getz, L.J.**, Dellaire, G. (2019). [CRISPR gene editing: Why we need Slow Science](https://theconversation.com/crispr-gene-editing-why-we-need-slow-science-113639), The Conversation.ca.

10. **Getz, L.J.**, Dellaire, G., Baylis, F. (2018). [Jiankui He: A Sorry Tale of High-Stakes Science](https://www.thehastingscenter.org/jiankui-sorry-tale-high-stakes-science/), The Hastings Center Forum Blog.

11. Baylis, F., Dellaire, G., **Getz, L.J.** (2018). [Why we are not ready for genetically designed babies](https://theconversation.com/why-we-are-not-ready-for-genetically-designed-babies-107756), The Conversation: Canada Edition. Reprinted in: The National Post and the Halifax Chronicle Herald.

12. **Getz, L.J.** (2018). [Thicker Than Water: Slow Movement on Blood Policy](https://impactethics.ca/2018/10/26/thicker-than-water-slow-movement-on-blood-policy/), Impact Ethics at Novel Tech Ethics.

13. **Getz, L.J.** (2018). [The Privacy Implications of Human DNA Sequencing](https://impactethics.ca/2018/05/11/the-privacy-implications-of-human-dna-sequencing/), Impact Ethics at Novel Tech Ethics.


# Selected Presentations

1. Build Back Better: The Chief Science Advisor’s Youth Council’s Roundtables to Envision A Post-Pandemic Future in the Canadian Science Community. Canadian Science Policy Conference, University of Ottawa, Ottawa, QC. October 2020.

2. Functional genomics of Vibrio pathogenesis and environmental persistence. Canadian Student Health Research Forum, University of Manitoba, Regina, MB. August 2020.

9. Creating LGBTQ+ Inclusive Spaces for Equitable Active Learning. Dalhousie Conference on University Teaching and Learning, Dalhousie University, Halifax, NS. May 2019
